spring.application.name=api-pedidos

spring.datasource.url=jdbc:postgresql://dpg-d720igjuibrs73d23bv0-a.oregon-postgres.render.com:5432/api_pedidos_frh1
spring.datasource.username=api_pedidos_frh1_user
spring.datasource.password=fhXrUXNH6ZctsB03oxJewJyLyflNZHBz
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

# Logging
logging.level.com.tienda.api=DEBUG
logging.level.org.springframework.web=INFO